INSERT INTO departement (nom)
VALUES ("Techniques de design d\'intérieur"),
        ("Techniques de la documentation"),
        ("Techniques d'hygiène dentaire'"),
        ("Techniques de diététique"),
        ("Techniques de soins infirmiers"),
        ("Techniques de soins infirmiers destiné aux infirmières auxiliaires"),
        ("Techniques de travail social"),
        ("Techniques d'éducation à l'enfance"),
        ("Techniques policières"),
        ("Techniques de génie mécanique"),
        ("Techniques de l'informatique"),
        ("Techniques de l'architecture"),
        ("Techniques de la mécanique du bâtiment (Génie du bâtiment)"),
        ("Techniques de la mécanique industrielle (maintenance)"),
        ("Techniques de génie civil"),
        ("Techniques de génie électrique - Automatisation et contrôle"),
        ("Techniques de génie électrique : Électrique programmable"),
        ("Techniques de génie industriel"),
        ("Techniques de génie métallurgique"),
        ("DEC-Bac en logistique"),
        ("DEC-Bac en marketing"),
        ("DEC-Bac en sciences comtables"),
        ("Gestion de commerces"),
        ("Gestion des opérations et de la chaine logistique"),
        ("Technique de comptabilité et de gestion"),
        ("Arts visuels"),
        ("Arts, lettres et communication - Théatre et création médias"),
        ("Musique"),
        ("Arts, lettres et communication - Langues"),
        ("Arts, lettres et communication - Littérature, arts et cinéma"),
        ("Histoire et civilisation"),
        ("Sciences de la nature"),
        ("Sciences humaines"),
        ("Sciences informatique et mathématiques"),
        ("Sciences, lettres et arts"),
        ("Sciences humaines avec préalables en mathématiques"),
        ("Tremplin DEC")
